# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: countries.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='countries.proto',
  package='',
  serialized_pb=_b('\n\x0f\x63ountries.proto*\xe5\x01\n\x0b\x43ountryCode\x12\x07\n\x03\x41LL\x10\x00\x12\x11\n\rNORTH_AMERICA\x10\x01\x12\x11\n\rSOUTH_AMERICA\x10\x02\x12\n\n\x06\x45UROPE\x10\x03\x12\n\n\x06\x41\x46RICA\x10\x04\x12\x08\n\x04\x41SIA\x10\x05\x12\r\n\tAUSTRALIA\x10\x06\x12\x11\n\rUNITED_STATES\x10\x07\x12\t\n\x05\x43HINA\x10\x08\x12\t\n\x05JAPAN\x10\t\x12\x0b\n\x07GERMANY\x10\n\x12\x12\n\x0eUNITED_KINGDOM\x10\x0b\x12\n\n\x06\x46RANCE\x10\x0c\x12\n\n\x06\x42RAZIL\x10\r\x12\t\n\x05ITALY\x10\x0e\x12\t\n\x05INDIA\x10\x0f')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_COUNTRYCODE = _descriptor.EnumDescriptor(
  name='CountryCode',
  full_name='CountryCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ALL', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NORTH_AMERICA', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SOUTH_AMERICA', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EUROPE', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AFRICA', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ASIA', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUSTRALIA', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNITED_STATES', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHINA', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JAPAN', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GERMANY', index=10, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNITED_KINGDOM', index=11, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FRANCE', index=12, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BRAZIL', index=13, number=13,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ITALY', index=14, number=14,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INDIA', index=15, number=15,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=20,
  serialized_end=249,
)
_sym_db.RegisterEnumDescriptor(_COUNTRYCODE)

CountryCode = enum_type_wrapper.EnumTypeWrapper(_COUNTRYCODE)
ALL = 0
NORTH_AMERICA = 1
SOUTH_AMERICA = 2
EUROPE = 3
AFRICA = 4
ASIA = 5
AUSTRALIA = 6
UNITED_STATES = 7
CHINA = 8
JAPAN = 9
GERMANY = 10
UNITED_KINGDOM = 11
FRANCE = 12
BRAZIL = 13
ITALY = 14
INDIA = 15


DESCRIPTOR.enum_types_by_name['CountryCode'] = _COUNTRYCODE


# @@protoc_insertion_point(module_scope)
