# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peers.proto

#pylint: skip-file

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='peers.proto',
  package='',
  serialized_pb=_b('\n\x0bpeers.proto\"6\n\tPeerSeeds\x12\x16\n\x0eserializedNode\x18\x01 \x03(\x0c\x12\x11\n\tsignature\x18\x02 \x02(\x0c')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PEERSEEDS = _descriptor.Descriptor(
  name='PeerSeeds',
  full_name='PeerSeeds',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='serializedNode', full_name='PeerSeeds.serializedNode', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signature', full_name='PeerSeeds.signature', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=69,
)

DESCRIPTOR.message_types_by_name['PeerSeeds'] = _PEERSEEDS

PeerSeeds = _reflection.GeneratedProtocolMessageType('PeerSeeds', (_message.Message,), dict(
  DESCRIPTOR = _PEERSEEDS,
  __module__ = 'peers_pb2'
  # @@protoc_insertion_point(class_scope:PeerSeeds)
  ))
_sym_db.RegisterMessage(PeerSeeds)


# @@protoc_insertion_point(module_scope)
